description: "Example using docker-compose files to output multiple streams at once"
name: compose-example-streams

steps:
  - type: compose
    composeFile: examples/docker-compose/example.compose.2.yml
