description: "Deploys application"
name: deploy
parameters: 
  - name: environment
    default: testing
    other_options:
      - production
  - name: AWS_ACCESS_KEY_ID
    secure: true
    
steps: 
  - 
    command: 
      - terraform
      - "--version"
    description: "Terraform Version"
    environment: 
      TFVAR_ENVIRONMENT: "${environment}"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    image: hashicorp/terraform
    type: run
  - 
    command: 
      - terraform
      - "--help"
    description: "Terraform Help"
    environment: 
      TFVAR_ENVIRONMENT: "${environment}"
    image: hashicorp/terraform
    type: run
  - 
    command: 
      - ls
      - "-al"
    description: "List directory"
    image: library/alpine
    type: run
    working_dir: ./tasks
  - 
    command: 
      - env
    description: "Show environment"
    environment: 
      WOO: "${environment}"
      ${environment}: AAAA
    image: library/alpine
    type: run
