language: python
sudo: required
services:
  - docker

env:
  matrix:
    - COMPONENT=backend
    - COMPONENT=web

script:
  - cd ${TRAVIS_BUILD_DIR}/${COMPONENT} && make install && make test && make build
