version: '3'

services:

  gogs:
    image: gogs/gogs
    expose: 
      - "3000"
      - "22"
    ports:
      - "3000:3000"
    volumes:
      - "./gogs-data:/data"
    networks:
      default:
        aliases:
          - gogs

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - "./api/swagger.json:/swagger.json"
    environment:
      SWAGGER_JSON: /swagger.json
    ports:
      - "8080:8080"

  architect:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: /bin/sh -c "eval `ssh-agent` && go run architect.go"
    restart: unless-stopped
    volumes:
      - "./:/go/src/github.com/velocity-ci/velocity/backend/"
      - "/tmp/velocity-workspace/logs:/tmp/velocity-workspace/logs"
    working_dir: /go/src/github.com/velocity-ci/velocity/backend/architect
    environment:
      JWT_SECRET: development
      PORT: 80
      ADMIN_PASSWORD: admin
    ports:
      - "80:80"
