version: '3'

services:
  architect:
    image: golang:1.9
    command: go run cmd/vci-architect/main.go
    working_dir: /go/src/github.com/velocity-ci/velocity/backend/
    environment:
      # LOG_LEVEL: debug
      ADMIN_PASSWORD: admin
      JWT_SECRET: local
      BUILDER_SECRET: local
      PORT: 80
    ports:
      - "80:80"
    volumes:
      - "./:/go/src/github.com/velocity-ci/velocity/backend/"
      - "./architect_data:/var/velocityci"

  builder:
    image: golang:1.9
    command: go run cmd/vci-builder/main.go
    working_dir: /go/src/github.com/velocity-ci/velocity/backend/
    environment:
      LOG_LEVEL: debug
      BUILDER_SECRET: local
      ARCHITECT_ADDRESS: http://architect
    volumes:
      - "./:/go/src/github.com/velocity-ci/velocity/backend/"
      - "/var/velocityci:/var/velocityci"
      - "/var/run/docker.sock:/var/run/docker.sock"
