version: '3'

services:

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - "./api/swagger.json:/swagger.json"
    environment:
      SWAGGER_JSON: /swagger.json
    ports:
      - "8080:8080"

  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: /bin/sh -c "eval `ssh-agent` && exec fresh"
    restart: unless-stopped
    volumes:
      - "./:/go/src/github.com/velocity-ci/velocity/backend/"
      - "/tmp/velocity-workspace/logs:/tmp/velocity-workspace/logs"
    working_dir: /go/src/github.com/velocity-ci/velocity/backend/api
    environment:
      JWT_SECRET: development
      PORT: 80
      SLAVE_SECRET: development
      ADMIN_PASSWORD: admin
    ports:
      - "80:80"

  slave:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: /bin/sh -c "eval `ssh-agent` && exec fresh"
    restart: unless-stopped
    volumes:
      - "./:/go/src/github.com/velocity-ci/velocity/backend/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/velocity-workspace/:/tmp/velocity-workspace/"
    working_dir: /go/src/github.com/velocity-ci/velocity/backend/slave
    links:
      - "api:api"
    environment:
      MASTER_ADDRESS: http://api
      SLAVE_SECRET: development
