description: "Builds API"
name: build-api
steps: 
  - type: build
    description: Build development image
    dockerfile: dev.Dockerfile
    context: ./backend
    tags:
      - veloci/backend-dev:latest
  
  - type: run
    description: Install dependencies
    image: veloci/backend-dev:latest
    mount_point: /go/src/github.com/velocity-ci/velocity/
    working_dir: backend
    command: ["glide", "install", "--strip-vendor"]

  - type: run
    description: Build binary
    image: golang
    mount_point: /go/src/github.com/velocity-ci/velocity/
    working_dir: backend
    environment:
      GOOS: linux
      CGO_ENABLED: 0
    command: ["go", "build", "-a", "-installsuffix", "cgo", "-o", "dist/velocity_api", "./api"]

  - type: build
    description: Build release image
    dockerfile: api.Dockerfile
    context: ./backend
    tags:
      - civelocity/api:${GIT_DESCRIBE}
      - civelocity/api:latest
