description: "Builds Slave"
name: build-slave
steps: 
  - type: clone
    submodule: false

  - type: build
    description: Build development image
    dockerfile: dev.Dockerfile
    context: ./backend
    tags:
      - civelocity/dev:latest
  
  - type: run
    description: Install dependencies
    image: civelocity/dev:latest
    mount_point: /go/src/github.com/velocity-ci/velocity/
    working_dir: backend
    command: ["dep", "ensure", "-v"]

  - type: run
    description: Prune dependencies
    image: civelocity/dev:latest
    mount_point: /go/src/github.com/velocity-ci/velocity/
    working_dir: backend
    command: ["dep", "prune"]

  - type: run
    description: Build binary
    image: golang
    mount_point: /go/src/github.com/velocity-ci/velocity/
    working_dir: backend
    environment:
      GOOS: linux
      CGO_ENABLED: 0
    command: ["go", "build", "-a", "-installsuffix", "cgo", "-o", "dist/velocity_slave", "./slave"]

  - type: build
    description: Build release image
    dockerfile: slave.Dockerfile
    context: ./backend
    tags:
      - civelocity/slave:${GIT_DESCRIBE}
      - civelocity/slave:latest
