description: "Builds Master"
name: build-master
steps: 
  - type: build
    description: Build development image
    dockerfile: dev.Dockerfile
    context: ./master
    tags:
      - veloci/master-dev:latest
  
  - type: run
    description: Install dependencies
    image: veloci/master-dev:latest
    mount_point: /go/src/github.com/velocity-ci/velocity/
    working_dir: master/velocity
    command: ["glide", "install", "--strip-vendor"]

  - type: run
    description: Build binary
    image: golang
    mount_point: /go/src/github.com/velocity-ci/velocity/
    working_dir: master/velocity
    command: ["go", "build", "-a", "-installsuffix", "cgo", "-o", "dist/velocity"]

  - type: build
    description: Build release image
    dockerfile: app.Dockerfile
    context: ./master
    tags:
      - veloci/master:latest
