description: "Hello Velocity"
name: hello-velocity
steps: 
  - type: clone
    submodule: false
      
  - type: run
    description: Hello Docker
    image: hello-world:latest

  - type: docker-compose
    composeFile: backend/docker-compose.test.yml