description: "Hello Velocity"
name: hello-velocity

parameters:
  - name: docker_hub_username
    secret: true
  - name: docker_hub_password
    secret: true

docker:
  registries:
    - use: civelocity/auth-docker-hub
      arguments:
        USERNAME: ${docker_hub_username}
        PASSWORD: ${docker_hub_password}

steps: 
  - type: build
    context: ./backend
    dockerfile: test.Dockerfile
    tags:
      - vjftw/test

  - type: push
    tags:
      - vjftw/test
