description: "Builds and publishes CLI"
name: publish-cli

steps: 

  - type: run
    description: Builds CLI releases
    image: golang:1.9
    command: scripts/build-cli.sh
    workingDir: backend
    mountPoint: /go/src/github.com/velocity-ci/velocity
