description: "Builds and publishes Architect"
name: publish-architect

parameters:
  - name: docker_hub_username
    secret: true
  - name: docker_hub_password
    secret: true

docker:
  registries:
    - use: https://github.com/velocity-ci/registry.docker-hub/releases/download/0.1.0/docker-hub
      arguments:
        USERNAME: ${docker_hub_username}
        PASSWORD: ${docker_hub_password}

steps: 
  - type: build
    description: Build release image
    dockerfile: build/docker/architect/Dockerfile
    context: ./backend
    tags:
      - civelocity/architect:${GIT_DESCRIBE}
      - civelocity/architect:latest
  - type: push
    tags:
      - civelocity/architect:${GIT_DESCRIBE}
      - civelocity/architect:latest
