description: "Builds and publishes Builder"
name: publish-builder

parameters:
  - name: docker_hub_username
    secret: true
  - name: docker_hub_password
    secret: true

docker:
  registries:
    - use: civelocity/auth-docker-hub
      arguments:
        USERNAME: ${docker_hub_username}
        PASSWORD: ${docker_hub_password}

steps: 
  - type: build
    description: Build release image
    dockerfile: build/docker/builder/Dockerfile
    context: ./backend
    tags:
      - civelocity/builder:${GIT_DESCRIBE}
      - civelocity/builder:latest
