description: "Builds and publishes CLI"

steps: 

  - type: run
    description: Builds CLI releases
    image: golang:1.11
    command: scripts/build-cli.sh
    workingDir: backend
    mountPoint: /go/src/github.com/velocity-ci/velocity
