version: '3'

services:

  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: /bin/sh -c "eval `ssh-agent` && exec fresh"
    restart: unless-stopped
    volumes:
      - "./:/go/src/github.com/velocity-ci/velocity/master/"
    working_dir: /go/src/github.com/velocity-ci/velocity/master/velocity
    environment:
      JWT_SECRET: development
      PORT: 80
    ports:
      - "80:80"
