version: '3'

services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: velocity_dev
      POSTGRES_PASSWORD: velocity_dev
      POSTGRES_DB: velocity_dev

  velocity_backend:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    command: /bin/sh -c "mix deps.get && /bin/wait-for-it.sh -t 120 postgres:5432 && mix ecto.create && mix ecto.migrate && mix phx.server"
    environment:
      SECRET_KEY_BASE: G9XBaZMFhtWDxAaowHCBrrDVq8xVB3sfro8xiGnFXfidldnvf
      GUARDIAN_SECRET_KEY: cQCWxKpcuixeB4ZAxCs04nrBGdKeJiHcmmCHbZPI6esGcLcfZVz1qw2796p3gWGA
      DATABASE_HOSTNAME: postgres
      DATABASE_USERNAME: velocity_dev
      DATABASE_PASSWORD: velocity_dev
      DATABASE_NAME: velocity_dev
      DATABASE_PORT: 5432
      PORT: 4000
      MIX_ENV: dev
    volumes:
      - "./velocity:/app"
    ports:
      - 4000:4000
    links:
      - database:postgres
    depends_on:
      - database
