version: '3'

services:

  a:
    image: busybox
    command: ping -c 3 c
    volumes:
      - "./:/app"
    links:
      - "b"

  b:
    image: alpine
    command: /bin/sh -c 'sleep 10s'
    networks:
      default:
        aliases:
          - "c"
